theme: jekyll-theme-hacker
future: true
timezone: Europe/Berlin
show_downloads: true
plugins:
  - jekyll-seo-tag
webmaster_verifications:
  google: cQnvtAcM35yBVl12YxYJ4oCa-z3bQsXcsfP4zNv_9OM

seo:
  name: A T.265 application
  type: BlogPosting,

